Repository Alfresco/generator-alfresco-adf-app, pull requests merged in 2021-05, with the labels that each got.

#304 Update branch for ADF 32347 and JS-API 4.4.0-3371
  package-lock.json
  package.json
Labels: PR: unreviewed

#306 Update branch for ADF 32569 and JS-API 4.4.0-3493
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#307 update the main readme with more info
  README.md
Labels: PR: partially-approved

#309 4.4.0
  app/templates/adf-cli-acs-aps-template/package.json
  app/templates/adf-cli-acs-template/package.json
  app/templates/adf-cli-activiti-acs-template/package.json
  app/templates/adf-cli-activiti-acs-template/src/app/services/debug-app-config.service.ts
  app/templates/adf-cli-activiti-acs-template/src/app/tasks/tasks.component.spec.ts
  app/templates/adf-cli-activiti-cloud-acs-template/package.json
  app/templates/adf-cli-activiti-cloud-acs-template/src/app/services/debug-app-config.service.ts
  app/templates/adf-cli-activiti-cloud-acs-template/src/app/tasks/tasks.component.spec.ts
  app/templates/adf-cli-activiti-cloud-template/package.json
  app/templates/adf-cli-activiti-cloud-template/src/app/tasks/tasks.component.spec.ts
  app/templates/adf-cli-activiti-template/package.json
  app/templates/adf-cli-activiti-template/src/app/services/debug-app-config.service.ts
  app/templates/adf-cli-aps-template/package.json
  package.json
Labels: PR: reviewed-approved
